// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWQZ2jra63JSGTCz5lUQw0A7NoVyhrTBU',
    appId: '1:968136753248:web:6dc111d7814b7221f58305',
    messagingSenderId: '968136753248',
    projectId: 'greendrop-esof',
    authDomain: 'greendrop-esof.firebaseapp.com',
    databaseURL: 'https://greendrop-esof-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'greendrop-esof.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp5IfqdxQTrW7bHi7Xcsk8q0_JSXSXUgY',
    appId: '1:968136753248:android:7d3a65b1962a1a68f58305',
    messagingSenderId: '968136753248',
    projectId: 'greendrop-esof',
    databaseURL: 'https://greendrop-esof-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'greendrop-esof.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBzNJjqsls6zRKyKT6kHdbxXh5LeH_dTo',
    appId: '1:968136753248:ios:fdd84ac052b11c54f58305',
    messagingSenderId: '968136753248',
    projectId: 'greendrop-esof',
    databaseURL: 'https://greendrop-esof-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'greendrop-esof.firebasestorage.app',
    iosClientId: '968136753248-n99d55tjnkgbji0v89n4biicpa4j66f2.apps.googleusercontent.com',
    iosBundleId: 'com.esof.greendrop',
  );
}
