name: greendrop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  provider: ^6.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  mockito: ^5.4.5
  change_app_package_name: ^1.5.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.9.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/greendrop.png"

flutter:
  uses-material-design: true

  assets:
    - assets/tree.png
    - assets/olive-tree.png
    - assets/sprout.png
    - assets/palms.png
    - assets/icon/greendrop.png
    - assets/icon/google.png
